### ISSUE TITLE
Brightfield inhomogeneity metric not computed on correct slice of image

### ISSUE THREAD

**Issue by kcw1375** [fenning-research-group/PASCAL#11]
Currently the inhomogeneity metric is computed only on a slice of the brightfield images to ignore parts outside the sample.
https://github.com/fenning-research-group/PASCAL/blob/45a479e4029c17791d0230e4c22e848e8014ce4a/frgpascal/analysis/brightfield.py#L9-L11

This used to make sense when our magnification was lower.
![good_slice](https://user-images.githubusercontent.com/73185476/197255774-dcd1db22-711c-46c7-9d24-d32c1e10c3b2.png)

However, now that we've increased our magnification for bf images, this slice ignores a large chunk of the sample, which means that morphological defects near the corners are neglected! 
![bad_slice](https://user-images.githubusercontent.com/73185476/197251042-68d2f20a-16b3-4131-9a27-ad31aa0bda54.png)

**Comment by kcw1375** [comment]
The above pull request is a fix which just expands the boundaries to cover the whole image.

Assuming our magnification stays consistent from now on (or at least the FOV is always  contained entirely within the sample), it should work, although it won't be backwards compatible.

**Comment by dnzckn** [comment]
can you instead pull request this to the cam swap branch, the cam swap branch assumes the higher mag optics

**Comment by kcw1375** [comment]
pull request created
