### ISSUE TITLE
plimg load doesnt work with different exposure times

### ISSUE THREAD

**Issue by dnzckn** [fenning-research-group/PASCAL#15]
the exposure time is saved to the PL image file name e.g. `*1000ms.tif` 

need a robust string reading to be able to load in pl images regardless of exposure, so something to look for just ms.tif for example, then to find the correct exposure.

![image](https://user-images.githubusercontent.com/49666626/200812346-ea7b4c20-feda-43c9-9774-9306881e2991.png)

**Comment by dnzckn** [comment]
in `PASCAL\frgpascal\analysis\processing.py`

**Comment by kcw1375** [comment]
pretty simple regex job. will there ever be more than one exposure per sample?
